### ISSUE TITLE
Post processing of uploaded files

### ISSUE THREAD

**Issue by CCCmarine** [bengarrett/html5Upload#8]
This is the nicest work around I have seen, many thanks.

How do you recommend triggering post processing of the uploaded files? 
I do server side image resizing and so on and cannot figure out how to start that (inc_imageprocess.cfm) once your upload is complete.

If I need to pass additional variables in the form how would I do that?

Thank you!

**Comment by bengarrett** [comment]
You would have to customise the client side JavaScript and get it to visit a CF template using form or url params to pass through any information.

There is a condition in `submit.js` that would be the most appropriate place to trigger it.
```if (xhr.status == 200) {}```
